/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/portfolioTest2/island.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Island.geometry} material={materials['Material.002']}/>
      <mesh
        geometry={nodes.Water.geometry}
        material={materials['Material.001']}
        position={[0, 0.56, -0.01]}
        scale={[2.22, 2.22, 2.22]}
      />
    </group>
  )
}

useGLTF.preload('/portfolioTest2/island.glb')
