/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, softShadows } from '@react-three/drei'


export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/portfoliotest2/island-1.glb')
  materials.Material.roughness = 1
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Island.geometry} material={materials.Material} receiveShadow/>
      <mesh
      receiveShadow
        geometry={nodes.Water.geometry}
        material={materials['Material.004']}
        position={[0, 0.56, -0.01]}
        scale={[2.22, 2.22, 2.22]}
      />
      <mesh
      castShadow
        geometry={nodes.tree1.geometry}
        material={nodes.tree1.material}
        position={[0.98, 1.15, 0.78]}
        scale={[0.05, 0.05, 0.05]}
      />
      <mesh
      castShadow
        geometry={nodes.tree1001.geometry}
        material={nodes.tree1001.material}
        position={[0.9, 1.2, -0.1]}
        rotation={[-Math.PI, 1.02, -Math.PI]}
        scale={[0.06, 0.06, 0.06]}
      />
      <mesh
      castShadow
        geometry={nodes.tree1002.geometry}
        material={nodes.tree1002.material}
        position={[0.9, 0.96, -1.58]}
        rotation={[-Math.PI, -0.73, -Math.PI]}
        scale={[0.04, 0.04, 0.04]}
      />
    </group>
  )
}

useGLTF.preload('/portfoliotest2/island-1.glb')


// materials.Material.roughness = 0.9
// materials['Material.004'].roughness = 0
// materials['Material.004'].metalness = 0.1
// materials['Material.004'].opacity = 0.1