/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/portfoliotest2/tree1.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[1.23, 9.46, -5.47]}>
        <mesh geometry={nodes.Icosphere_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Icosphere_2.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/portfoliotest2/tree1.glb')
